# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build amd64 binary

on:
  workflow_call:
    inputs:
      upload-binary:
        required: false
        type: boolean
        default: false
    secrets:
      DOCKERHUB_TOKEN:
        required: true
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Publish to Dockerhub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ameypar
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      run: ./build.sh

    - name: Build docker
      run: ./build-docker.sh

    - name: Push the docker image
      run: docker push ameypar/k8s-vault-initializer

    - name: Start minikube
      id: minikube
      uses: medyagh/setup-minikube@master

    - name: Run tests
      run: ./test.sh

    - uses: actions/upload-artifact@v3
      if: ${{ inputs.upload-binary }}
      with:
        name: k8s-vault-initializer
        path: ./build/k8s-vault-initializer

