name: "Create release"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yml
    with:
      upload-binary: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  create-release:
    name: "Create release"
    runs-on: "ubuntu-latest"
    needs: Build

    steps:
      # ...
      - uses: actions/download-artifact@v3
        with:
          name: k8s-secret-creator

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            k8s-vault-initializer
